version: "3.8"
name: badminton-hub-api

services:
  badminton-hub:
    build:
      context: .
      dockerfile: config/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      # - DB_Name=badminton_hub
      # - MONGO_URI=mongodb://mongo:27017

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml