version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_Name=badminton_hub
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo
    networks:
      - badminton-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - badminton-network

volumes:
  mongo_data:

networks:
  badminton-network:
    driver: bridge
